# Generated by Django 2.2.17 on 2021-02-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20210207_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='xpAmount',
            field=models.IntegerField(default=10),
        ),
    ]
